/**
 * Default ruleset — 6 attributes, 4 classes, 4 races.
 * Loaded automatically for any new project. All entries are editable/removable.
 */

import type { AttributeDef, ClassDef, RaceDef, SpellDef, StatusEffectDef, Ruleset } from './engine-types'

export const DEFAULT_ATTRIBUTES: AttributeDef[] = [
  { id: 'attr.might',      name: 'Might',      abbr: 'MGT', min: 3, max: 18, default: 10, description: 'Physical power; increases melee damage and max HP.' },
  { id: 'attr.agility',    name: 'Agility',    abbr: 'AGL', min: 3, max: 18, default: 10, description: 'Speed and dexterity; affects initiative, hit chance, and defense.' },
  { id: 'attr.intellect',  name: 'Intellect',  abbr: 'INT', min: 3, max: 18, default: 10, description: 'Mental acuity; boosts arcane spell power and max MP.' },
  { id: 'attr.spirit',     name: 'Spirit',     abbr: 'SPI', min: 3, max: 18, default: 10, description: 'Spiritual force; boosts divine spell power and max MP.' },
  { id: 'attr.endurance',  name: 'Endurance',  abbr: 'END', min: 3, max: 18, default: 10, description: 'Resilience; primary contributor to max HP.' },
  { id: 'attr.luck',       name: 'Luck',       abbr: 'LCK', min: 3, max: 18, default: 10, description: 'Fortune; increases critical hit chance and loot quality.' },
]

export const DEFAULT_CLASSES: ClassDef[] = [
  {
    id: 'class.fighter',
    name: 'Fighter',
    icon: '⚔️',
    color: '#c0392b',
    description: 'A seasoned warrior who excels in melee combat and can wear heavy armor.',
    hitDie: 10,
    spellDie: 0,
    spellSchools: [],
    allowedEquip: ['weapon', 'offhand', 'head', 'body', 'hands', 'feet', 'ring', 'amulet'],
    weaponKinds: ['blade', 'axe', 'mace', 'bow', 'spear'],
    attrGrowth: { might: 1, endurance: 1 },
    attrModifiers: { might: 2, endurance: 2 },
  },
  {
    id: 'class.mage',
    name: 'Mage',
    icon: '🔮',
    color: '#8e44ad',
    description: 'A scholarly spellcaster who channels arcane energies. Frail but devastating.',
    hitDie: 4,
    spellDie: 8,
    spellSchools: ['arcane'],
    allowedEquip: ['weapon', 'ring', 'amulet'],
    weaponKinds: ['staff', 'wand', 'dagger'],
    startingSpells: ['spell.fire_bolt', 'spell.sleep_spell'],
    attrGrowth: { intellect: 2 },
    attrModifiers: { intellect: 3 },
  },
  {
    id: 'class.cleric',
    name: 'Cleric',
    icon: '✝️',
    color: '#f39c12',
    description: 'A devoted priest who wields divine magic and can heal the party.',
    hitDie: 6,
    spellDie: 6,
    spellSchools: ['divine'],
    allowedEquip: ['weapon', 'offhand', 'head', 'body', 'hands', 'feet', 'ring', 'amulet'],
    weaponKinds: ['mace', 'staff', 'hammer'],
    startingSpells: ['spell.cure_light', 'spell.cure_poison'],
    attrGrowth: { spirit: 2 },
    attrModifiers: { spirit: 3 },
  },
  {
    id: 'class.rogue',
    name: 'Rogue',
    icon: '🗡️',
    color: '#27ae60',
    description: 'A quick and cunning adventurer skilled in stealth and precision strikes.',
    hitDie: 6,
    spellDie: 0,
    spellSchools: [],
    allowedEquip: ['weapon', 'offhand', 'head', 'body', 'hands', 'feet', 'ring', 'amulet'],
    weaponKinds: ['dagger', 'blade', 'bow'],
    attrGrowth: { agility: 2 },
    attrModifiers: { agility: 3, luck: 1 },
  },
]

export const DEFAULT_RACES: RaceDef[] = [
  {
    id: 'race.human',
    name: 'Human',
    icon: '🧑',
    color: '#e8d5b0',
    description: 'Versatile and adaptable. Slight bonuses across the board.',
    attrModifiers: { might: 1, agility: 1, intellect: 1, spirit: 1, endurance: 1, luck: 1 },
    traits: ['Adaptable'],
  },
  {
    id: 'race.elf',
    name: 'Elf',
    icon: '🧝',
    color: '#7dcea0',
    description: 'Graceful and magically gifted. High intellect and agility but less endurance.',
    attrModifiers: { agility: 2, intellect: 2, spirit: 1, endurance: -2 },
    resistances: { dark: 0.1 },
    traits: ['Keen Senses', 'Night Vision'],
  },
  {
    id: 'race.dwarf',
    name: 'Dwarf',
    icon: '🧔',
    color: '#b07d4a',
    description: 'Stout and resilient. Superior endurance and might, but slower than most.',
    attrModifiers: { might: 2, endurance: 3, agility: -2, luck: 1 },
    resistances: { poison: 0.15 },
    traits: ['Stonecunning', 'Poison Resistance'],
  },
  {
    id: 'race.halfling',
    name: 'Halfling',
    icon: '🧑‍🦯',
    color: '#f0c078',
    description: 'Small but nimble and surprisingly lucky. Masters of the unexpected.',
    attrModifiers: { agility: 2, luck: 3, might: -2 },
    traits: ['Halfling Luck', 'Small Frame'],
  },
]

export const DEFAULT_STATUS_EFFECTS: StatusEffectDef[] = [
  {
    id: 'status.poisoned',
    name: 'Poisoned',
    icon: '☠️',
    color: '#2ecc71',
    description: 'Takes poison damage each turn.',
    kind: 'dot',
    durationTurns: 3,
    blocksAction: false,
    tickEffects: [{ t: 'damage', dmgType: 'poison', amount: '1d4', canCrit: false }],
  },
  {
    id: 'status.asleep',
    name: 'Asleep',
    icon: '💤',
    color: '#9b59b6',
    description: 'Cannot act while asleep.',
    kind: 'control',
    durationTurns: 3,
    blocksAction: true,
  },
  {
    id: 'status.regen',
    name: 'Regenerating',
    icon: '💚',
    color: '#27ae60',
    description: 'Recovers HP each turn.',
    kind: 'hot',
    durationTurns: 4,
    blocksAction: false,
    tickEffects: [{ t: 'heal', amount: '1d6' }],
  },
]

export const DEFAULT_SPELLS: SpellDef[] = [
  {
    id: 'spell.cure_light',
    name: 'Cure Light Wounds',
    icon: '✨',
    color: '#f1c40f',
    school: 'divine',
    level: 1,
    mpCost: 4,
    target: 'ally',
    inCombat: true,
    outOfCombat: true,
    description: 'Heals a single ally for 1d8+2 HP.',
    effects: [{ t: 'heal', amount: '1d8+2' }],
  },
  {
    id: 'spell.cure_poison',
    name: 'Cure Poison',
    icon: '🍃',
    color: '#2ecc71',
    school: 'divine',
    level: 1,
    mpCost: 2,
    target: 'ally',
    inCombat: true,
    outOfCombat: true,
    description: 'Removes poison from a single ally.',
    effects: [{ t: 'cure', status: 'status.poisoned' }],
  },
  {
    id: 'spell.group_heal',
    name: 'Mass Cure',
    icon: '💛',
    color: '#f39c12',
    school: 'divine',
    level: 3,
    mpCost: 8,
    target: 'allAllies',
    inCombat: true,
    outOfCombat: true,
    description: 'Heals all allies for 1d6 HP.',
    effects: [{ t: 'heal', amount: '1d6' }],
  },
  {
    id: 'spell.regen',
    name: 'Regenerate',
    icon: '💚',
    color: '#27ae60',
    school: 'divine',
    level: 2,
    mpCost: 3,
    target: 'ally',
    inCombat: true,
    outOfCombat: true,
    description: 'Grants an ally the Regenerating status for 4 turns.',
    effects: [{ t: 'status', status: 'status.regen' }],
  },
  {
    id: 'spell.fire_bolt',
    name: 'Fire Bolt',
    icon: '🔥',
    color: '#e74c3c',
    school: 'arcane',
    level: 1,
    mpCost: 5,
    target: 'enemy',
    inCombat: true,
    outOfCombat: false,
    description: 'Hurls a bolt of fire at one enemy for 1d10 fire damage.',
    effects: [{ t: 'damage', dmgType: 'fire', amount: '1d10', canCrit: true }],
  },
  {
    id: 'spell.fireball',
    name: 'Fireball',
    icon: '💥',
    color: '#e67e22',
    school: 'arcane',
    level: 3,
    mpCost: 10,
    target: 'allEnemies',
    inCombat: true,
    outOfCombat: false,
    description: 'Engulfs all enemies in flame for 2d6 fire damage.',
    effects: [{ t: 'damage', dmgType: 'fire', amount: '2d6', canCrit: true }],
  },
  {
    id: 'spell.sleep_spell',
    name: 'Sleep',
    icon: '💤',
    color: '#9b59b6',
    school: 'arcane',
    level: 1,
    mpCost: 4,
    target: 'enemy',
    inCombat: true,
    outOfCombat: false,
    description: 'Attempts to put one enemy to sleep (60% chance).',
    effects: [{ t: 'status', status: 'status.asleep', chance: 0.6 }],
  },
  {
    id: 'spell.poison',
    name: 'Poison',
    icon: '☠️',
    color: '#2ecc71',
    school: 'arcane',
    level: 2,
    mpCost: 4,
    target: 'enemy',
    inCombat: true,
    outOfCombat: false,
    description: 'Poisons one enemy, dealing 1d4 damage per turn for 3 turns.',
    effects: [{ t: 'status', status: 'status.poisoned', chance: 0.75 }],
  },
]

export function makeDefaultRuleset(startMapId = 'map1'): Ruleset {
  return {
    meta: {
      title: 'My Dungeon',
      version: '0.1',
      startMapId,
      startPosition: { x: 0, y: 0, facing: 'N' },
      partySize: 6,
      rows: 2,
      permadeath: false,
      startingGold: 100,
    },
    attributes: DEFAULT_ATTRIBUTES,
    classes: DEFAULT_CLASSES,
    races: DEFAULT_RACES,
    items: [],
    spells: DEFAULT_SPELLS,
    statusEffects: DEFAULT_STATUS_EFFECTS,
    enemies: [],
    encounterTables: [],
    lootTables: [],
    shops: [],
  }
}
